### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by a1498396553** [yyyzzzhao/VEUS#3]
Hello, is it convenient to provide data sets?

**Comment by yyyzzzhao** [comment]
Due to the involvement of patient privacy, please contact the corresponding author (Jianqiao Zhou) for accessing data. thank you.

**Comment by a1498396553** [comment]
Hello, Prof. Zhao may not have replied due to some reason, can you provide a sample of the dataset? This is my e-mail 1498396553@qq.com
Thank you very much!

**Comment by yyyzzzhao** [comment]
The sample has sent to your email. Contact me if you have any doubts.

**Comment by yyyzzzhao** [comment]
The sample has sent to your email. Contact me if you have any doubts.

**Comment by a1498396553** [comment]
I have received it ,thank you
