### ISSUE TITLE
Original data

### ISSUE THREAD

**Issue by zhanglepy** [yyyzzzhao/VEUS#5]
Would you like to send the original data of this paper to our laboratory? We are voluntarily bound by any intellectual property rights or patient confidentiality obligations, and will handle it according to the guidelines of institutions and departments, and submit a material transfer agreement. More importantly, in the future, our research results will cite your paper and receive high praise. Thank you very much for replying to my email.

**Comment by yyyzzzhao** [comment]
Thanks for your interest to our work. We collect data from hospitals and are bound by hospital data management regulations. So please contact Prof. Jianqiao Zhou to request permission to use the data.

**Comment by yyyzzzhao** [comment]
> Would you like to send the original data of this paper to our laboratory? We are voluntarily bound by any intellectual property rights or patient confidentiality obligations, and will handle it according to the guidelines of institutions and departments, and submit a material transfer agreement. More importantly, in the future, our research results will cite your paper and receive high praise. Thank you very much for replying to my email.

Thanks for your interest to our work. We collect data from hospitals and are bound by hospital data management regulations. So please contact Prof. Jianqiao Zhou to request permission to use the data.
